---
source: Rmd
title: "Summarizing branch length information"
teaching: 5
exercises: 5
questions:
- "How do I summarize infromation from different source chronograms?"
- "How do I choose a preferred source chronogram?"
objectives:
- "Understanding the depth of uncertainty around age estimates."
keypoints:
- "Source chronograms have a wide range of variation in age estimates."
---
```{r, eval = TRUE, echo = FALSE, message = FALSE, results = 'hide', warning = FALSE}
source("../bin/chunk-options.R")
# apes <- c("Pongo", "Pan", "Gorilla", "Hoolock", "Homo")
# resolved_names <- rotl::tnrs_match_names(apes)
# apes_dr <- datelife::get_datelife_result(resolved_names$unique_name, get_spp_from_taxon = TRUE)
my_taxa <- c("amphibians", "canis", "felis", "delphinidae", "spheniscidae")
resolved_names <- rotl::tnrs_match_names(my_taxa)
rownames(resolved_names) <- resolved_names$unique_name
canis_node_info <- rotl::tol_node_info(resolved_names["Canis",]$ott_id)
canis_node_subtree <- rotl::tol_subtree(node_id = canis_node_info$node_id, label = "name")
canis_dr <- datelife::get_datelife_result(canis_node_subtree)
```

We can summarize it.
```{r, eval = TRUE, results = 'hide', message = FALSE}
canis_phylo_median <-  datelife::summarize_datelife_result(canis_dr, summary_format = "phylo_median")
```
```{r plot60, eval = TRUE, results= 'asis', warning= FALSE, error = TRUE, fig.height = 10}
canis_phylo_median
ape::plot.phylo(canis_phylo_median, cex = 1.2)
ape::axisPhylo()
````

> ## Challenge! Get other types of summary opentree_chronograms
>
> > Hint: Use the argument summary_format = "phylo_sdm" from the funtion `summarize_datelife_result()`
> >
> > ## Solution
> > ```{r, eval = TRUE, results = 'hide', message = FALSE}
> > canis_phylo_sdm <-  datelife::summarize_datelife_result(canis_dr, summary_format = "phylo_sdm")
> > ```
> > ```{r plot61, eval = TRUE, results= 'asis', warning= FALSE, error = TRUE, fig.height = 10}
> > canis_phylo_sdm
> > ape::plot.phylo(canis_phylo_sdm, cex = 1.2)
> > ape::axisPhylo()
> > ````
> {: .solution}
{: .challenge}

#### You can also try the web browser of [datelife](http://datelife.org/query/).
